<?php
require_once 'conn.php';

try {
    // 1. Create Activity Logs Table
    $sql_table = "CREATE TABLE IF NOT EXISTS activity_logs (
        log_id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        action_type VARCHAR(50),
        affected_record_id INT,
        details TEXT,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    )";
    
    if (!$conn->query($sql_table)) {
        throw new Exception("Error creating table: " . $conn->error);
    }
    echo "Activity logs table created successfully.<br>";

    // 2. Create Triggers
    // We need to know the current user ID. Triggers run in MySQL context, so they don't know the PHP session user.
    // A common workaround is to have a 'users' table and maybe log the DB user, but here we want the App User.
    // Since we can't easily pass the PHP Session ID to the Trigger, we will implement the logging in the PHP Application Layer 
    // as per the 'Activity Log Generation' requirement which mentions 'database trigger(s)'.
    // However, strict interpretation of 'database trigger(s)' to record 'User ID' is difficult without a stored procedure or session variable.
    // I will implement the triggers to capture the *action* and *timestamp*, and maybe use a session variable if possible, 
    // OR I will implement the logging in the PHP code to ensure User ID is captured correctly, which is often more practical.
    // 
    // BUT, the requirement says: "Implement database trigger(s) to automatically record changes... ensuring auditability."
    // and "The Activity Log (generated by database triggers) must record the User ID..."
    // To do this with triggers, we'd need to set a MySQL session variable before the query.
    // SET @current_user_id = ?;
    
    // Let's try to set up the triggers assuming @current_user_id will be set.
    
    $triggers = [
        "after_employee_insert" => "
            CREATE TRIGGER IF NOT EXISTS after_employee_insert 
            AFTER INSERT ON employees 
            FOR EACH ROW 
            BEGIN
                INSERT INTO activity_logs (user_id, action_type, affected_record_id, details, timestamp)
                VALUES (@current_user_id, 'INSERT', NEW.idemployees, CONCAT('Added employee: ', NEW.first_name, ' ', NEW.last_name), NOW());
            END",
            
        "after_employee_update" => "
            CREATE TRIGGER IF NOT EXISTS after_employee_update 
            AFTER UPDATE ON employees 
            FOR EACH ROW 
            BEGIN
                INSERT INTO activity_logs (user_id, action_type, affected_record_id, details, timestamp)
                VALUES (@current_user_id, 'UPDATE', NEW.idemployees, CONCAT('Updated employee: ', NEW.first_name, ' ', NEW.last_name), NOW());
            END",
            
        "after_employee_delete" => "
            CREATE TRIGGER IF NOT EXISTS after_employee_delete 
            AFTER DELETE ON employees 
            FOR EACH ROW 
            BEGIN
                INSERT INTO activity_logs (user_id, action_type, affected_record_id, details, timestamp)
                VALUES (@current_user_id, 'DELETE', OLD.idemployees, CONCAT('Deleted employee: ', OLD.first_name, ' ', OLD.last_name), NOW());
            END"
    ];

    foreach ($triggers as $name => $sql) {
        // Drop trigger if exists to ensure we update it
        $conn->query("DROP TRIGGER IF EXISTS $name");
        
        if (!$conn->query($sql)) {
            throw new Exception("Error creating trigger $name: " . $conn->error);
        }
        echo "Trigger $name created successfully.<br>";
    }

} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}
?>
